name: Get PR Details from Push Event

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - closed

jobs:
  get-pr-details:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'cherry-pick-hotfix') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use a PAT with the required permissions
          script: |
            const currentTarget = context.payload.pull_request.base.ref;
            const latestVSCRelease = '${{ steps.get-latest-release.outputs.latest_vsc_release }}';
            const latestVSRelease = '${{ steps.get-latest-release.outputs.latest_vs_release }}';
            const prNumber = context.payload.pull_request.number;
            const prTitle = context.payload.pull_request.title;
            const prAuthor = context.payload.pull_request.user.login;
            console.log(`PR Number: ${prNumber}`);
            console.log(`PR Title: ${prTitle}`);
            console.log(`PR Author: ${prAuthor}`);
            console.log(`Current Target: ${currentTarget}`);